In [377]:
import torch
torch.__version__

'1.12.1+cu113'

In [378]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [379]:
scalar.ndim

0

In [380]:
scalar.item()

7

In [381]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [382]:
vector.ndim

1

In [383]:
vector.shape

torch.Size([2])

In [384]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [385]:
matrix.ndim

2

In [386]:
matrix.shape

torch.Size([2, 2])

In [387]:
tensor = torch.tensor([[[1,2],[3,4]],[[4,5],[6,7]]])
tensor

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])

In [388]:
tensor.ndim

3

In [389]:
tensor.shape

torch.Size([2, 2, 2])

In [390]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.8826, 0.5284, 0.1675, 0.1511],
        [0.1357, 0.8059, 0.3653, 0.9296],
        [0.4802, 0.1235, 0.0422, 0.4864]])

In [391]:
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [392]:
zeros.dtype

torch.float32

In [393]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [394]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [395]:
ten_ones.dtype, ten_ones.device

(torch.int64, device(type='cpu'))

In [396]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [397]:
tensor*10

tensor([10, 20, 30])

In [398]:
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [399]:
tensor = torch.add(tensor, 10)

In [400]:
tensor*tensor

tensor([1, 4, 9])

In [401]:
torch.tensor([[1,2],[3,4]])*torch.tensor([2, 3])

tensor([[ 2,  6],
        [ 6, 12]])

In [402]:
tensor = torch.tensor([1,2,3])

In [403]:
tensor * tensor

tensor([1, 4, 9])

In [404]:
torch.matmul(tensor, tensor)

tensor(14)

In [405]:
A = torch.rand((3,4))
B = torch.rand((3,4))

In [406]:
torch.matmul(A, B.T)

tensor([[1.2630, 1.3029, 0.5321],
        [0.8463, 0.8862, 0.3026],
        [1.5671, 1.1032, 0.5996]])

In [407]:
linear = torch.nn.Linear(2, 6)

In [408]:
output = linear(torch.rand(4,2))

In [409]:
output.shape

torch.Size([4, 6])

In [410]:
X = torch.rand(10)
X

tensor([0.7478, 0.8839, 0.5542, 0.8208, 0.3932, 0.4745, 0.8997, 0.1468, 0.1531,
        0.1521])

In [411]:
X.sum()

tensor(5.2262)

In [412]:
X.mean()

tensor(0.5226)

In [413]:
X.max()

tensor(0.8997)

In [414]:
X.min()

tensor(0.1468)

In [415]:
X.argmax()

tensor(6)

In [416]:
X.argmin()

tensor(7)

In [417]:
X = torch.arange(10, 100, 10)
X.dtype

torch.int64

In [418]:
Q = X.type(torch.float32)
Q.dtype

torch.float32

In [419]:
X = torch.rand((10))
X

tensor([0.9215, 0.0841, 0.7736, 0.2042, 0.9856, 0.2405, 0.1716, 0.1048, 0.9893,
        0.9515])

In [420]:
X.argsort()

tensor([1, 7, 6, 3, 5, 2, 0, 9, 4, 8])

In [421]:
X = torch.rand((3,3))
X

tensor([[0.9981, 0.0705, 0.5440],
        [0.8070, 0.2753, 0.0830],
        [0.7162, 0.9803, 0.2179]])

In [422]:
X.det()

tensor(0.2936)

In [423]:
y = X.reshape(9)
y

tensor([0.9981, 0.0705, 0.5440, 0.8070, 0.2753, 0.0830, 0.7162, 0.9803, 0.2179])

In [424]:
z = X.view(9)
z

tensor([0.9981, 0.0705, 0.5440, 0.8070, 0.2753, 0.0830, 0.7162, 0.9803, 0.2179])

In [425]:
z[2]=5
z

tensor([0.9981, 0.0705, 5.0000, 0.8070, 0.2753, 0.0830, 0.7162, 0.9803, 0.2179])

In [426]:
X

tensor([[0.9981, 0.0705, 5.0000],
        [0.8070, 0.2753, 0.0830],
        [0.7162, 0.9803, 0.2179]])

In [427]:
y

tensor([0.9981, 0.0705, 5.0000, 0.8070, 0.2753, 0.0830, 0.7162, 0.9803, 0.2179])

In [428]:
x = torch.rand(3,3)
x

tensor([[0.9492, 0.0356, 0.5412],
        [0.3367, 0.3209, 0.1219],
        [0.7174, 0.7983, 0.6704]])

In [429]:
y = x.reshape(9)
y

tensor([0.9492, 0.0356, 0.5412, 0.3367, 0.3209, 0.1219, 0.7174, 0.7983, 0.6704])

In [430]:
z=x.view(9)
z

tensor([0.9492, 0.0356, 0.5412, 0.3367, 0.3209, 0.1219, 0.7174, 0.7983, 0.6704])

In [431]:
x[1,2] = 5
x

tensor([[0.9492, 0.0356, 0.5412],
        [0.3367, 0.3209, 5.0000],
        [0.7174, 0.7983, 0.6704]])

In [432]:
y

tensor([0.9492, 0.0356, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [433]:
z

tensor([0.9492, 0.0356, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [434]:
y[0]=5
y

tensor([5.0000, 0.0356, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [435]:
x

tensor([[5.0000, 0.0356, 0.5412],
        [0.3367, 0.3209, 5.0000],
        [0.7174, 0.7983, 0.6704]])

In [436]:
z

tensor([5.0000, 0.0356, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [437]:
z[1]=5
z

tensor([5.0000, 5.0000, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [438]:
x

tensor([[5.0000, 5.0000, 0.5412],
        [0.3367, 0.3209, 5.0000],
        [0.7174, 0.7983, 0.6704]])

In [439]:
y

tensor([5.0000, 5.0000, 0.5412, 0.3367, 0.3209, 5.0000, 0.7174, 0.7983, 0.6704])

In [440]:
x = torch.rand(3,3)
x

tensor([[0.8120, 0.9457, 0.8032],
        [0.0809, 0.7423, 0.3624],
        [0.9849, 0.0879, 0.3628]])

In [441]:
y = x.reshape(9)
y

tensor([0.8120, 0.9457, 0.8032, 0.0809, 0.7423, 0.3624, 0.9849, 0.0879, 0.3628])

In [442]:
y[0]=5
y, x

(tensor([5.0000, 0.9457, 0.8032, 0.0809, 0.7423, 0.3624, 0.9849, 0.0879, 0.3628]),
 tensor([[5.0000, 0.9457, 0.8032],
         [0.0809, 0.7423, 0.3624],
         [0.9849, 0.0879, 0.3628]]))

In [443]:
X = torch.arange(4).reshape(2,2)
X

tensor([[0, 1],
        [2, 3]])

In [444]:
torch.stack([X,X,X], dim=1)

tensor([[[0, 1],
         [0, 1],
         [0, 1]],

        [[2, 3],
         [2, 3],
         [2, 3]]])

In [445]:
X = torch.arange(5).reshape(1,5)
X, X.shape

(tensor([[0, 1, 2, 3, 4]]), torch.Size([1, 5]))

In [446]:
X = X.squeeze()
X, X.shape

(tensor([0, 1, 2, 3, 4]), torch.Size([5]))

In [447]:
X = X.unsqueeze(dim=0)
X, X.shape

(tensor([[0, 1, 2, 3, 4]]), torch.Size([1, 5]))

In [448]:
X = torch.rand((256, 256, 3))
Q = X.permute(2, 0, 1)
X.shape, Q.shape

(torch.Size([256, 256, 3]), torch.Size([3, 256, 256]))

In [449]:
X = torch.arange(16).reshape(1, 4, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]])

In [450]:
X[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [451]:
X[0][2]

tensor([ 8,  9, 10, 11])

In [452]:
X[0][2][1]

tensor(9)

In [453]:
X[:,:, 3]

tensor([[ 3,  7, 11, 15]])

In [454]:
X[:,2,1:3]

tensor([[ 9, 10]])