In [238]:
import torch
torch.__version__

'1.12.1+cu113'

In [239]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [240]:
scalar.ndim

0

In [241]:
scalar.item()

7

In [242]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [243]:
vector.ndim

1

In [244]:
vector.shape

torch.Size([2])

In [245]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [246]:
matrix.ndim

2

In [247]:
matrix.shape

torch.Size([2, 2])

In [248]:
tensor = torch.tensor([[[1,2],[3,4]],[[4,5],[6,7]]])
tensor

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])

In [249]:
tensor.ndim

3

In [250]:
tensor.shape

torch.Size([2, 2, 2])

In [251]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.8549, 0.5509, 0.2868, 0.2063],
        [0.4451, 0.3593, 0.7204, 0.0731],
        [0.9699, 0.1078, 0.8829, 0.4132]])

In [252]:
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [253]:
zeros.dtype

torch.float32

In [254]:
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [255]:
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [256]:
ten_ones.dtype, ten_ones.device

(torch.int64, device(type='cpu'))

In [257]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [258]:
tensor*10

tensor([10, 20, 30])

In [259]:
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [260]:
tensor = torch.add(tensor, 10)

In [261]:
tensor*tensor

tensor([1, 4, 9])

In [262]:
torch.tensor([[1,2],[3,4]])*torch.tensor([2, 3])

tensor([[ 2,  6],
        [ 6, 12]])

In [263]:
tensor = torch.tensor([1,2,3])

In [264]:
tensor * tensor

tensor([1, 4, 9])

In [265]:
torch.matmul(tensor, tensor)

tensor(14)

In [266]:
A = torch.rand((3,4))
B = torch.rand((3,4))

In [267]:
torch.matmul(A, B.T)

tensor([[1.5635, 0.9548, 1.6533],
        [1.5798, 1.0473, 1.5865],
        [1.6509, 1.0595, 1.7429]])

In [268]:
linear = torch.nn.Linear(2, 6)

In [269]:
output = linear(torch.rand(4,2))

In [270]:
output.shape

torch.Size([4, 6])

In [271]:
X = torch.rand(10)
X

tensor([0.7738, 0.2259, 0.3826, 0.9717, 0.5921, 0.5352, 0.6686, 0.3781, 0.9278,
        0.0922])

In [272]:
X.sum()

tensor(5.5479)

In [273]:
X.mean()

tensor(0.5548)

In [274]:
X.max()

tensor(0.9717)

In [275]:
X.min()

tensor(0.0922)

In [276]:
X.argmax()

tensor(3)

In [277]:
X.argmin()

tensor(9)

In [278]:
X = torch.arange(10, 100, 10)
X.dtype

torch.int64

In [279]:
Q = X.type(torch.float32)
Q.dtype

torch.float32

In [280]:
X = torch.rand((10))
X

tensor([0.3625, 0.4136, 0.2943, 0.3762, 0.8099, 0.7743, 0.5278, 0.9356, 0.1470,
        0.2019])

In [281]:
X.argsort()

tensor([8, 9, 2, 0, 3, 1, 6, 5, 4, 7])

In [282]:
X = torch.rand((3,3))
X

tensor([[0.7259, 0.4731, 0.0444],
        [0.1539, 0.1956, 0.8861],
        [0.7264, 0.8868, 0.1278]])

In [283]:
X.det()

tensor(-0.2573)

In [284]:
y = X.reshape(9)
y

tensor([0.7259, 0.4731, 0.0444, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278])

In [285]:
z = X.view(9)
z

tensor([0.7259, 0.4731, 0.0444, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278])

In [286]:
z[2]=5
z

tensor([0.7259, 0.4731, 5.0000, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278])

In [287]:
X

tensor([[0.7259, 0.4731, 5.0000],
        [0.1539, 0.1956, 0.8861],
        [0.7264, 0.8868, 0.1278]])

In [288]:
y

tensor([0.7259, 0.4731, 5.0000, 0.1539, 0.1956, 0.8861, 0.7264, 0.8868, 0.1278])

In [289]:
x = torch.rand(3,3)
x

tensor([[0.0125, 0.1721, 0.5535],
        [0.4012, 0.1849, 0.8640],
        [0.3388, 0.2108, 0.7310]])

In [290]:
y = x.reshape(9)
y

tensor([0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 0.8640, 0.3388, 0.2108, 0.7310])

In [291]:
z=x.view(9)
z

tensor([0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 0.8640, 0.3388, 0.2108, 0.7310])

In [292]:
x[1,2] = 5
x

tensor([[0.0125, 0.1721, 0.5535],
        [0.4012, 0.1849, 5.0000],
        [0.3388, 0.2108, 0.7310]])

In [293]:
y

tensor([0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [294]:
z

tensor([0.0125, 0.1721, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [295]:
y[0]=5
y

tensor([5.0000, 0.1721, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [296]:
x

tensor([[5.0000, 0.1721, 0.5535],
        [0.4012, 0.1849, 5.0000],
        [0.3388, 0.2108, 0.7310]])

In [297]:
z

tensor([5.0000, 0.1721, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [298]:
z[1]=5
z

tensor([5.0000, 5.0000, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [299]:
x

tensor([[5.0000, 5.0000, 0.5535],
        [0.4012, 0.1849, 5.0000],
        [0.3388, 0.2108, 0.7310]])

In [300]:
y

tensor([5.0000, 5.0000, 0.5535, 0.4012, 0.1849, 5.0000, 0.3388, 0.2108, 0.7310])

In [301]:
x = torch.rand(3,3)
x

tensor([[0.3653, 0.8188, 0.6192],
        [0.5123, 0.6050, 0.1243],
        [0.2325, 0.2650, 0.2171]])

In [302]:
y = x.reshape(9)
y

tensor([0.3653, 0.8188, 0.6192, 0.5123, 0.6050, 0.1243, 0.2325, 0.2650, 0.2171])

In [303]:
y[0]=5
y, x

(tensor([5.0000, 0.8188, 0.6192, 0.5123, 0.6050, 0.1243, 0.2325, 0.2650, 0.2171]),
 tensor([[5.0000, 0.8188, 0.6192],
         [0.5123, 0.6050, 0.1243],
         [0.2325, 0.2650, 0.2171]]))

In [304]:
X = torch.arange(4).reshape(2,2)
X

tensor([[0, 1],
        [2, 3]])

In [305]:
torch.stack([X,X,X], dim=1)

tensor([[[0, 1],
         [0, 1],
         [0, 1]],

        [[2, 3],
         [2, 3],
         [2, 3]]])

In [306]:
X = torch.arange(5).reshape(1,5)
X, X.shape

(tensor([[0, 1, 2, 3, 4]]), torch.Size([1, 5]))

In [307]:
X = X.squeeze()
X, X.shape

(tensor([0, 1, 2, 3, 4]), torch.Size([5]))

In [308]:
X = X.unsqueeze(dim=0)
X, X.shape

(tensor([[0, 1, 2, 3, 4]]), torch.Size([1, 5]))

In [309]:
X = torch.rand((256, 256, 3))
Q = X.permute(2, 0, 1)
X.shape, Q.shape

(torch.Size([256, 256, 3]), torch.Size([3, 256, 256]))

In [310]:
X = torch.arange(16).reshape(1, 4, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]])

In [311]:
X[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [312]:
X[0][2]

tensor([ 8,  9, 10, 11])

In [313]:
X[0][2][1]

tensor(9)

In [314]:
X[:,:, 3]

tensor([[ 3,  7, 11, 15]])

In [315]:
X[:,2,1:3]

tensor([[ 9, 10]])

In [316]:
import numpy as np

In [317]:
a = np.array([11,2])
t= torch.from_numpy(a)
a, t

(array([11,  2]), tensor([11,  2]))

In [318]:
a += 1
a, t

(array([12,  3]), tensor([12,  3]))

In [319]:
t = torch.ones(7)
t

tensor([1., 1., 1., 1., 1., 1., 1.])

In [320]:
n = t.numpy()
n

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [321]:
t += 1
t, n

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [322]:
torch.manual_seed(42)
C = torch.rand(2,3)
torch.manual_seed(42)
D = torch.rand(2,3)
C == D

tensor([[True, True, True],
        [True, True, True]])

In [323]:
!nvidia-smi

Sun Sep 18 19:23:40 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    33W /  70W |    816MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [324]:
torch.cuda.is_available()

True

In [325]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [326]:
torch.cuda.device_count()

1

In [327]:
X = torch.rand(4,5)
X.device

device(type='cpu')

In [328]:
X.to(device)

tensor([[0.2566, 0.7936, 0.9408, 0.1332, 0.9346],
        [0.5936, 0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695]], device='cuda:0')

In [329]:
X.device

device(type='cpu')

In [330]:
X = X.to(device)
X.device

device(type='cuda', index=0)

In [331]:
X.cpu().numpy()

array([[0.25657248, 0.7936413 , 0.94077146, 0.13318592, 0.9345981 ],
       [0.59357965, 0.86940444, 0.5677153 , 0.74109405, 0.4294045 ],
       [0.8854429 , 0.57390445, 0.26658005, 0.62744915, 0.26963168],
       [0.44136357, 0.29692084, 0.8316855 , 0.10531491, 0.26949483]],
      dtype=float32)

In [332]:
torch.manual_seed(0)
X = torch.rand((7,7))
X

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [333]:
torch.manual_seed(0)
Z = torch.rand((1,7))
Z

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [334]:
X @ Z.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [335]:
torch.cuda.manual_seed(1234)

In [336]:
torch.manual_seed(1234)
a = torch.rand(2,3).to(device)
torch.manual_seed(1234)
b = torch.rand(2,3).to(device)
a, b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [337]:
m = torch.matmul(a, b.T)
m

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [338]:
m.min()

tensor(0.2161, device='cuda:0')

In [339]:
m.max()

tensor(0.6287, device='cuda:0')

In [340]:
m.argmin()

tensor(1, device='cuda:0')

In [341]:
m.argmax()

tensor(3, device='cuda:0')

In [342]:
torch.manual_seed(7)
C = torch.rand((1,1,1,10))
C, C.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))

In [343]:
N = C.squeeze()
N, N.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]), torch.Size([10]))